version: '3'

services:
  robot-servers:
    container_name: robot-servers
    image: robot-servers
    command: bash -c "start-server-manager && tail -f /dev/null" #This starts the server manager and hangs
    restart: always

  robo-gym:
    container_name: robo-gym
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: robo-gym
    restart: always
    entrypoint: tail -f /dev/null
    depends_on:
      - robot-servers
  #   stdin_open: true
  #   tty: true
